### ISSUE TITLE
Não foi possível atualizar o banco de dados da Paghiper para a versão 1.4

### ISSUE THREAD

**Issue by linkoficial** [LinkNacional/whmcs-boleto-pix#10]
Olá,
após atualizar o módulo da versão original para o fork da linknacional (v2.5.3) visualizei no log a seguinte mensagem no primeiro update de status (através da opção "Log de Transações do Gateway" do WHMCS):

_"Não foi possível atualizar o banco de dados da Paghiper para a versão 1.4. Por favor cheque se o usuário MySQL tem permissões para alterar a tabela mod_paghiper"_

**Comment by brunoferreiralkn** [comment]
Olá, boa tarde.

@linkoficial,

parece que você veio de uma versão anterior do PagHiper e o gateway não conseguiu atualizar as mudanças da versão 2.5.3 automaticamente devido a permissões de operação no banco de dados.

O seu WHMCS tem o phpMyAdmin?

Se sim, acesse a tabela `mod_paghiper`, clique na aba "SQL", no topo, insira o script abaixo:

`ALTER TABLE `mod_paghiper` ADD COLUMN lock_id varchar(64) DEFAULT NULL AFTER bacen_url;`

e clique em "Go" ou em "Executar", a depender do idioma do seu phpMyAdmin.

**Comment by linkoficial** [comment]
Obrigado por detalhar o procedimento,  porém obtive erro de coluna duplicada ao executar conforme log do phpmyadmin:
"#1060 - Nome da coluna 'lock_id' duplicado"

**Comment by brunoferreiralkn** [comment]
Então, parece que a coluna foi criada. Consegue efetuar uma mudança de status para validar?

**Comment by linkoficial** [comment]
@brunoferreiralkn realmente, parece que ele se "auto corrigiu", verifiquei novamente o log e isso ocorreu apenas na primeira alteração de status, nas demais o erro não foi registrado.
Mas observei esta mensagem agora: "O ID de requosição associado PIX não é desta sessão. Erro 0x004682 Thread ID: a2424d44c7b9739e358d5d0c42b921cf Lock: 32c4369c4230d1ddb19929827c91d7c6"

Devo me preocupar com isso, ou pode ser ignorado?

**Comment by brunoferreiralkn** [comment]
@linkoficial,

ode ignorar. Isso ocorre quando o Pix venceu, ou algo semelhante.

Consegue gerar um Pix ou boleto numa outra fatura para confirmar?

**Comment by linkoficial** [comment]
Muito obrigado @brunoferreiralkn 
Realizei os testes e agora parece estar tudo perfeito.
Parabéns pelo desenvolvimento e admirável suporte!
