### ISSUE TITLE
Atualizei para a versão mais nova e agora quando tento gerar o boleto, aparece a mensagem abaixo.

### ISSUE THREAD

**Issue by eseixas** [LinkNacional/whmcs-boleto-pix#5]
TypeError: array_shift(): Argument #1 ($array) must be of type array, bool given in /modules/gateways/paghiper/inc/helpers/gateway_functions.php:772
Stack trace:
#0 /modules/gateways/paghiper/inc/helpers/gateway_functions.php(772): array_shift()
#1 /modules/gateways/paghiper/inc/helpers/process_payment.php(323): generate_paghiper_billet()
#2 /modules/gateways/paghiper.php(299): require_once('...')
#3 {main}

**Comment by souzadavi** [comment]
Aparentemente esta ligada a razão social, como esta a configuração no módulo? tente deixar o campo em branco na configurações do módulo.

![image](https://user-images.githubusercontent.com/636225/227638887-7f16a4a0-e0cb-4c78-a305-6f17ab8f3e5b.png)

**Comment by brunoferreiralkn** [comment]
Boa tarde, @eseixas. Lançamos uma nova versão para corrigir o problema.

Por favor, faço o download dela aqui: [whmcs-boleto-pix.zip](https://github.com/LinkNacional/whmcs-boleto-pix/releases/download/v2.5.2/whmcs-boleto-pix.zip)
